# Generated by Django 4.1.3 on 2022-11-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('ADM', 'Administrador'), ('USR', 'Usuarios')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Chapa', models.IntegerField()),
                ('Tipo_de_usuario', models.CharField(choices=[('ADM', 'Administrador'), ('USR', 'Usuarios')], max_length=100)),
            ],
        ),
    ]
